# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3.3.0
        with:
         node-version: "14.X"
      - name: install deps
        run: npm install
      - name: build app
        run: npm run build
      - name: copy dist file with sftp
        uses: wlixcc/SFTP-Deploy-Action@v1.2.2
        with:
          server: ${{ secrets.HUAWEIYUN_HOST }}
          username: ${{ secrets.HUAWEIYUN_USER }}
          password: ${{ secrets.HUAWEIYUN_PASSWORD }}
          ssh_private_key: ${{ secrets.HUAWEIYUN_SSH_PRIVATE_KEY }}
          port: 22
          local_path: "docs/"
          remote_path: ${{ secrets.HUAWEIYUN_TARGET }}
